language: bash
script: 
  - |
    make _build
    make _lint_lib
    bash tool/shpec test/*
cache: apt
before_install:
  - |
    get_shellcheck() {
      (
      for v
      do
        pkg=shellcheck_${v}_amd64.deb
        url="http://ftp.debian.org/debian/pool/main/s/shellcheck/"
        wget $url/$pkg || continue
        echo $pkg
        break
      done
      )
    }

    pkg=$( get_shellcheck 0.3.5-3 0.3.4-3 )
    sudo dpkg -i $pkg
    sudo apt-get install -y gpp bash tree
