language: bash
env: 
  matrix:
    - LINT=true
    - SHELL=bash
matrix:
  fast_finish: true
script: make
cache: apt
before_install:
  - |
    get_shellcheck() {
      (
      for v
      do
        pkg=shellcheck_${v}_amd64.deb
        url="http://ftp.debian.org/debian/pool/main/s/shellcheck/"
        wget $url/$pkg || continue
        echo $pkg
        break
      done
      )
    }
    install_shell(){
      echo "Install $SHELL"
      sudo apt-get update -qq
      sudo apt-get install -y $SHELL
    }

    if ${LINT:-false}; then
      pkg=$( get_shellcheck 0.3.5-3 0.3.4-3 )
      sudo dpkg -i $pkg
    elif ! type $SHELL > /dev/null; then
      install_shell
    fi

    sudo apt-get install -y gpp
